format long e

file=fopen("~/ist-tcfe/t2/data.txt",'r');
t=importdata("~/ist-tcfe/t2/data.txt",'\t',14);

R1=sscanf(char (t(4,1)), "Values: R1 = %e")*1000;
R2=sscanf(char (t(5,1)), "R2 = %e")*1000;
R3=sscanf(char (t(6,1)), "R3 = %e")*1000;
R4=sscanf(char (t(7,1)), "R4 = %e")*1000;
R5=sscanf(char (t(8,1)), "R5 = %e")*1000;
R6=sscanf(char (t(9,1)), "R6 = %e")*1000;
R7=sscanf(char (t(10,1)), "R7 = %e")*1000;
Vs=sscanf(char (t(11,1)), "Vs = %e");
C=sscanf(char (t(12,1)), "C = %e")/1000000;
Kb=sscanf(char (t(13,1)), "Kb = %e")/1000;
Kd=sscanf(char (t(14,1)), "Kc = %e")*1000;

fclose (file);

% writing the data in first.cir for the first simulation in ngspice
file2=fopen("first.cir",'w');

fprintf(file2, ".OP\n\n");

fprintf(file2,"*INDEPENDENT VOLTAGE SOURCE, CONNECTED TO GROUND. AND NODE X. VALUE IN VOLTS.\n");
fprintf(file2, "Vs 1 0 %e \n\n",Vs);

fprintf(file2,"*RESISTORS, CONNECTED BETWEEN THE NODES X X. RESISTANCE VALUE IN OHM.\n");
fprintf(file2, "R1 1 2 %e \n",R1);
fprintf(file2, "R2 3 2 %e \n",R2);
fprintf(file2, "R3 2 5 %e \n",R3);
fprintf(file2, "R4 5 0 %e \n",R4);
fprintf(file2, "R5 5 6 %e \n",R5);
fprintf(file2, "R6 9 0 %e \n",R6);
fprintf(file2, "R7 7 8 %e \n\n",R7);

fprintf(file2,"*DEPENDENT CURRENT SOURCE. CONNECTED TO NODES X & X. DEPENDS OF THE VOLTAGE BETWEEN THE NODES 1 AND 4. VALUE AMPLIFIED BY CONSTANT Z. VALUE IN AMPERES.\n");
fprintf(file2, "Gb 6 3 (2,5) %e \n\n",Kb);

fprintf(file2,"*DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X . DEPENDS OF THE CURRENT THATS FLOWS IN THE VAUX SOURCE. IS AMPLIFIED BY CONSTANTE Y. VALUE IN VOLTS.\n");
fprintf(file2, "Hd 5 8 Vaux %e \n\n",Kd);


fprintf(file2,"*INDEPENDENT VOLTAGE SOURCE TO USE IN THE DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file2, "Vaux 9 7 0 \n\n");

fprintf(file2,"*CAPACITOR. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file2, "C1 6 8 %e \n\n",C);

fprintf(file2, ".END\n\n");

fclose(file2);


%Insertion of the resitors' values generated by datagen.py
%R1 = 1.04111259479e3;
%R2 = 2.09945227782e3; 
%R3 = 3.13109125645e3; 
%R4 = 4.11947040212e3; 
%R5 = 3.1155879392e3; 
%R6 = 2.04799381798e3; 
%R7 = 1.02754401839e3;

% Calculation of the inverse of the resistors. Useful to the Node Method
G1=1/R1;
G2=1/R2;
G3=1/R3;
G4=1/R4;
G5=1/R5;
G6=1/R6;
G7=1/R7;

% Insertion of the remaining values generated by datagen.py
%Vs = 5.06871572779; 
%C = 1.04127523824e-3; 
%Kb = 7.28747116393e-3; 
%Kd = 8.11568444746e3;


% Insertion of the matrices that will allow us to calculate the voltages of 
% each node by the Node Method
D =[1 0 0 0 0 0 0 0;
    -G1 G1+G2+G3 -G2 0 -G3 0 0 0;
    0 -Kb-G2 G2 0 Kb 0 0 0;
    0 0 0 1 0 0 0 0;
    0 -G3 0 -G4 G3+G4+G5 -G5 -G7 G7;
    0 Kb 0 0 -Kb-G5 G5 0 0;
    0 0 0 -G6 0 0 G6+G7 -G7;
    0 0 0 Kd*G6 -1 0 -Kd*G6 1];

E=[Vs; 0 ; 0; 0 ; 0 ; 0 ; 0; 0];

% D*F=E <=>
F=inv(D)*E;

Vx=F(6)-F(8)

% Creating a table in the mat folder with the voltages results of the Node Method
printf ("nos_TAB\n");
printf ("V1 = %e \n", F(1));
printf ("V2 = %e \n", F(2));
printf ("V3 = %e \n", F(3));
printf ("V4 = %e \n", F(4));
printf ("V5 = %e \n", F(5));
printf ("V6 = %e \n", F(6));
printf ("V7 = %e \n", F(7));
printf ("V8 = %e \n", F(8));
printf ("nos_END\n");


% writing the data in third.cir for the third simulation in ngspice

file3=fopen("third.cir",'w');

fprintf(file3, ".OP\n\n");

fprintf(file3,"*INDEPENDENT VOLTAGE SOURCE, CONNECTED TO GROUND. AND NODE X. VALUE IN VOLTS.\n");
fprintf(file3, "Vs 1 0 0 \n\n");

fprintf(file3,"*RESISTORS, CONNECTED BETWEEN THE NODES X X. RESISTANCE VALUE IN OHM.\n");
fprintf(file3, "R1 1 2 %e \n",R1);
fprintf(file3, "R2 3 2 %e \n",R2);
fprintf(file3, "R3 2 5 %e \n",R3);
fprintf(file3, "R4 5 0 %e \n",R4);
fprintf(file3, "R5 5 6 %e \n",R5);
fprintf(file3, "R6 9 0 %e \n",R6);
fprintf(file3, "R7 7 8 %e \n\n",R7);

fprintf(file3,"*DEPENDENT CURRENT SOURCE. CONNECTED TO NODES X & X. DEPENDS OF THE VOLTAGE BETWEEN THE NODES 1 AND 4. VALUE AMPLIFIED BY CONSTANT Z. VALUE IN AMPERES.\n");
fprintf(file3, "Gb 6 3 (2,5) %e \n\n",Kb);

fprintf(file3,"*DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X . DEPENDS OF THE CURRENT THATS FLOWS IN THE VAUX SOURCE. IS AMPLIFIED BY CONSTANTE Y. VALUE IN VOLTS.\n");
fprintf(file3, "Hd 5 8 Vaux %e \n\n",Kd);


fprintf(file3,"*INDEPENDENT VOLTAGE SOURCE TO USE IN THE DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file3, "Vaux 9 7 0 \n\n");

fprintf(file3,"*CAPACITOR. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file3, "C1 6 8 %e \n\n",C);

fprintf(file3,".IC v(6)=%e v(8)=%e\n\n",F(6), F(8));

fprintf(file3, ".END\n\n");

fclose(file3);



% writing the data in fourth.cir for the fourth simulation in ngspice

file4=fopen("fourth.cir",'w');

fprintf(file4, ".OP\n\n");

fprintf(file4,"*INDEPENDENT VOLTAGE SOURCE, CONNECTED TO GROUND. AND NODE X. VALUE IN VOLTS.\n");
fprintf(file4, "Vs 1 0 0.0 ac 1.0 sin(0 1 1000) \n\n");

fprintf(file4,"*RESISTORS, CONNECTED BETWEEN THE NODES X X. RESISTANCE VALUE IN OHM.\n");
fprintf(file4, "R1 1 2 %e \n",R1);
fprintf(file4, "R2 3 2 %e \n",R2);
fprintf(file4, "R3 2 5 %e \n",R3);
fprintf(file4, "R4 5 0 %e \n",R4);
fprintf(file4, "R5 5 6 %e \n",R5);
fprintf(file4, "R6 9 0 %e \n",R6);
fprintf(file4, "R7 7 8 %e \n\n",R7);

fprintf(file4,"*DEPENDENT CURRENT SOURCE. CONNECTED TO NODES X & X. DEPENDS OF THE VOLTAGE BETWEEN THE NODES 1 AND 4. VALUE AMPLIFIED BY CONSTANT Z. VALUE IN AMPERES.\n");
fprintf(file4, "Gb 6 3 (2,5) %e \n\n",Kb);

fprintf(file4,"*DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X . DEPENDS OF THE CURRENT THATS FLOWS IN THE VAUX SOURCE. IS AMPLIFIED BY CONSTANTE Y. VALUE IN VOLTS.\n");
fprintf(file4, "Hd 5 8 Vaux %e \n\n",Kd);


fprintf(file4,"*INDEPENDENT VOLTAGE SOURCE TO USE IN THE DEPENDENT VOLTAGE SOURCE. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file4, "Vaux 9 7 0 \n\n");

fprintf(file4,"*CAPACITOR. CONNECTED TO NODES X & X. VALUE = 0 VOLTS\n");
fprintf(file4, "C1 6 8 %e \n\n",C);

fprintf(file4,".IC v(6)=%e v(8)=%e\n\n",F(6), F(8));

fprintf(file4, ".END\n\n");

fclose(file4);



X =[1 0 0 0 0 0 0 0 0;
    -G1 G1+G2+G3 -G2 0 -G3 0 0 0 0;
    0 -Kb-G2 G2 0 Kb 0 0 0 0;
    0 0 0 1 0 0 0 0 0;
    0 -G3 0 -G4 G3+G4+G5 -G5 -G7 G7 -1;
    0 Kb 0 0 -Kb-G5 G5 0 0 1;
    0 0 0 -G6 0 0 G6+G7 -G7 0;
    0 0 0 Kd*G6 -1 0 -Kd*G6 1 0;
    0 0 0 0 0 1 0 -1 0];

Y=[0; 0 ; 0; 0 ; 0 ; 0 ; 0; 0; Vx];

% D*F=E <=>
Z=inv(X)*Y



%A=[1 0 0 0 0 0 0 0;
%    -G1 G1+G2+G3 -G2 0 -G3 0 0 0;
%    0 -Kb-G2 G2 0 Kb 0 0 0;
%    0 0 0 1 0 0 0 0;
%    0 -G3 0 -G4 G3+G4+G5 -G5 -G7 G7;
%    0 Kb 0 0 -Kb-G5 G5 0 0;
%    0 0 0 -G6 0 0 G6+G7 -G7;
 %   0 0 0 Kd*G6 -1 0 -Kd*G6 1];


%B=[0; 0 ; 0; 0 ; 0 ; 0 ; Vx; 0; 0];

% D*F=E <=>
%C=inv(A)*B

